services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pilot-coupon-dispatch-service
    restart: unless-stopped
    env_file:
      - .env
    environment:
      SPRING_CONFIG_IMPORT: "optional:file:/app/.env[.properties]"
    network_mode: "host"
    volumes:
      - ./.env:/app/.env:ro
      - ./logs:/app/logs
      - ./static:/app/static
